# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    issuer: {{ .Values.issuerUrl }}
    storage:
      type: kubernetes
      config:
        {{- if not .Values.kubeconfig }}
        inCluster: true
        {{- else }}
        kubeConfigFile: /etc/kubeconfig/kubeconfig
        {{- end }}
    web:
      http: "0.0.0.0:{{ .Values.containerPort }}"
      allowedOrigins:
      {{- range .Values.dashboardOrigins }}
        - {{ . }}
      {{- end }}
    oauth2:
      skipApprovalScreen: true
      responseTypes:
      - token
      - code
      - id_token
    staticClients:
    - id: dashboard
      redirectURIs:
      {{- range .Values.dashboardOrigins }}
        - "{{ . }}/auth/callback"
        - "{{ . }}/callback"
      {{- end }}
      name: Gardener Dashboard
      secret: {{ .Values.dashboardClientSecret }}
    - id: kube-kubectl
      public: true
      trustedPeers:
      - dashboard
{{- if .Values.additionalTrustedPeers }}
{{ toYaml .Values.additionalTrustedPeers | trim | indent 6 }}
{{- end }}
      name: Kubectl
      secret: {{ .Values.kubectlClientSecret }}
{{- if .Values.additionalStaticClients }}
{{ toYaml .Values.additionalStaticClients | trim | indent 4 }}
{{- end }}
{{- if .Values.staticPasswords }}
    enablePasswordDB: true
    staticPasswords:
{{ toYaml .Values.staticPasswords | indent 6 }}
{{ else }}
    enablePasswordDB: false
    staticPasswords: []
{{- end -}}
{{- if .Values.connectors }}
    connectors:
{{ toYaml .Values.connectors | indent 6 }}
{{ else }}
    connectors: []
{{- end -}}
